name: swarapp
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.8+21

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  contacts_service: ^0.6.3
  flutter_svg: ^0.22.0
  assets_audio_player: ^3.0.3+3
  flutter_hooks: ^0.17.0
  stacked: ^2.1.0
  stacked_services: ^0.8.5
  get_it: ^6.1.1
  get: ^4.1.4 
  dio: ^4.0.0
  shared_preferences: ^2.0.5
  device_info: ^2.0.0
  styled_widget: ^0.3.0
  flutter_form_builder: ^7.0.0
  flutter_appauth: ^1.0.0
  jwt_decoder: ^2.0.1
  path_provider: ^2.0.1
  jiffy: ^4.1.0
  camerawesome: ^0.3.0-nullsafety
  image_crop: ^0.4.0
  file_picker: ^3.0.1
  image_picker: ^0.8.4+4
  permission_handler: ^6.0.1
  android_path_provider: ^0.2.1
  progress_indicators: ^1.0.0
  extended_image: ^4.1.0
  share: ^2.0.1
  google_maps_flutter: ^2.0.5
  geolocator: ^7.0.3
  google_maps_webservice: ^0.0.19
  google_maps_place_picker: ^2.0.0-nullsafety.3
  syncfusion_flutter_pdfviewer: ^19.1.64-beta
  url_launcher: ^6.0.4
  pinch_zoom: ^0.1.0
  syncfusion_flutter_datagrid: ^19.1.67-beta
  collection: ^1.15.0
  connectycube_sdk: ^2.0.7
  connectivity: ^3.0.6
  fluttertoast: ^8.0.7
  firebase_core: ^1.10.0
  firebase_messaging: ^11.1.0
  flutter_local_notifications: ^5.0.0+1
  flutter_voip_push_notification:
    git:
      url: https://github.com/blackdragon0603/flutter_voip_push_notification.git
      ref: master
  flutter_call_kit:
    git:
      url: https://github.com/raj457036/flutter_call_kit.git
      ref: master

  connectycube_flutter_call_kit: 
    path: ./connectycube-flutter-call-kit
    
  platform_device_id: ^1.0.1
  firebase_dynamic_links: ^2.0.6
  filesize: ^2.0.1
  showcaseview: ^0.1.5
  photo_view: ^0.12.0
  wakelock: ^0.5.2
  # flutter_ringtone_player: ^3.0.0
  flutter_inapp_purchase: 5.0.3
  proximity_sensor: ^1.0.2
  badges: ^2.0.1
  image_cropper: ^1.4.1
  new_version: ^0.2.3
  workmanager: ^0.4.1
  audioplayers: ^0.20.1
  advance_pdf_viewer_fork: ^2.0.0
  table_calendar: ^3.0.2
  flutter_inappwebview: ^5.3.2
  multiselect: ^0.0.4
  video_player: ^2.2.11
  screen:
    git:
      url: https://github.com/daniloapr/flutter_screen.git
      ref: master
  doctor_module:
    path: ./packages/doctor_module
  documents_module:
    path: ./packages/documents_module
  member_module:
    path: ./packages/member_module
  user_module:
    path: ./packages/user_module
  flutter_ringtone_player: ^3.1.1
  flutter_video_info: ^1.2.0
  video_thumbnail: ^0.4.3
  hand_signature: ^2.1.1
  form_builder_extra_fields: ^7.0.0
  form_builder_validators: ^7.3.0
  syncfusion_flutter_sliders: ^19.4.52
  flutter_widget_from_html: ^0.8.0
  video_compress: ^3.1.0
  file_selector: ^0.8.3
  back_button_interceptor: ^5.0.2
  flutter_rating_stars: ^1.0.3+4
  razorpay_flutter: ^1.3.0
  overlay_tooltip: ^0.1.0
  flutter_pin_code_fields: ^1.1.0

dependency_overrides:
  flutter_webrtc: 0.6.10
  
dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
        - asset: fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: fonts/Montserrat-Bold.ttf
          weight: 700
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
